-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
  vim.cmd("highlight clear")
end
vim.g.colors_name = "github-sam"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Define" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@lsp.type.class", { link = "Structure" })
hi(0, "@lsp.type.comment", { link = "Comment" })
hi(0, "@lsp.type.decorator", { link = "Function" })
hi(0, "@lsp.type.enum", { link = "Structure" })
hi(0, "@lsp.type.enumMember", { link = "Constant" })
hi(0, "@lsp.type.function", { link = "Function" })
hi(0, "@lsp.type.interface", { link = "Structure" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.method", { link = "Function" })
hi(0, "@lsp.type.namespace", { link = "Structure" })
hi(0, "@lsp.type.parameter", { link = "Identifier" })
hi(0, "@lsp.type.property", { link = "Identifier" })
hi(0, "@lsp.type.struct", { link = "Structure" })
hi(0, "@lsp.type.type", { link = "Type" })
hi(0, "@lsp.type.typeParameter", { link = "Typedef" })
hi(0, "@lsp.type.variable", { link = "Identifier" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@text.literal", { link = "Comment" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "BufferLineBackground", { bg = "#e0e0e0", fg = "#6a737d" })
hi(0, "BufferLineBuffer", { bg = "#e0e0e0", fg = "#6a737d" })
hi(0, "BufferLineBufferSelected", { bg = "#ffffff", bold = true, fg = "#24292e", italic = true })
hi(0, "BufferLineBufferVisible", { bg = "#eaeaea", fg = "#6a737d" })
hi(0, "BufferLineCloseButton", { bg = "#e0e0e0", fg = "#6a737d" })
hi(0, "BufferLineCloseButtonSelected", { bg = "#ffffff", fg = "#24292e" })
hi(0, "BufferLineCloseButtonVisible", { bg = "#eaeaea", fg = "#6a737d" })
hi(0, "BufferLineDevIconLuaInactive", { bg = "#eaeaea", fg = "#366b8a" })
hi(0, "BufferLineDiagnostic", { bg = "#e0e0e0", fg = "#5d656e" })
hi(0, "BufferLineDiagnosticSelected", { bg = "#ffffff", bold = true, fg = "#1f2428", italic = true })
hi(0, "BufferLineDiagnosticVisible", { bg = "#eaeaea", fg = "#5d656e" })
hi(0, "BufferLineDuplicate", { bg = "#e0e0e0", fg = "#646d76", italic = true })
hi(0, "BufferLineDuplicateSelected", { bg = "#ffffff", fg = "#646d76", italic = true })
hi(0, "BufferLineDuplicateVisible", { bg = "#eaeaea", fg = "#646d76", italic = true })
hi(0, "BufferLineError", { bg = "#e0e0e0", fg = "#6a737d", sp = "#ff0000" })
hi(0, "BufferLineErrorDiagnostic", { bg = "#e0e0e0", fg = "#5d656e", sp = "#e00000" })
hi(
  0,
  "BufferLineErrorDiagnosticSelected",
  { bg = "#ffffff", bold = true, fg = "#e00000", italic = true, sp = "#e00000" }
)
hi(0, "BufferLineErrorDiagnosticVisible", { bg = "#eaeaea", fg = "#5d656e" })
hi(0, "BufferLineErrorSelected", { bg = "#ffffff", bold = true, fg = "#ff0000", italic = true, sp = "#ff0000" })
hi(0, "BufferLineErrorVisible", { bg = "#eaeaea", fg = "#6a737d" })
hi(0, "BufferLineFill", { bg = "#cccccc", fg = "#6a737d" })
hi(0, "BufferLineGroupLabel", { bg = "#6a737d", fg = "#cccccc" })
hi(0, "BufferLineGroupSeparator", { bg = "#cccccc", fg = "#6a737d" })
hi(0, "BufferLineHint", { bg = "#e0e0e0", fg = "#6a737d", sp = "#d3d3d3" })
hi(0, "BufferLineHintDiagnostic", { bg = "#e0e0e0", fg = "#5d656e", sp = "#b9b9b9" })
hi(
  0,
  "BufferLineHintDiagnosticSelected",
  { bg = "#ffffff", bold = true, fg = "#b9b9b9", italic = true, sp = "#b9b9b9" }
)
hi(0, "BufferLineHintDiagnosticVisible", { bg = "#eaeaea", fg = "#5d656e" })
hi(0, "BufferLineHintSelected", { bg = "#ffffff", bold = true, fg = "#d3d3d3", italic = true, sp = "#d3d3d3" })
hi(0, "BufferLineHintVisible", { bg = "#eaeaea", fg = "#6a737d" })
hi(0, "BufferLineIndicatorSelected", { bg = "#ffffff", fg = "#41484f" })
hi(0, "BufferLineIndicatorVisible", { bg = "#eaeaea", fg = "#eaeaea" })
hi(0, "BufferLineInfo", { bg = "#e0e0e0", fg = "#6a737d", sp = "#add8e6" })
hi(0, "BufferLineInfoDiagnostic", { bg = "#e0e0e0", fg = "#5d656e", sp = "#98beca" })
hi(
  0,
  "BufferLineInfoDiagnosticSelected",
  { bg = "#ffffff", bold = true, fg = "#98beca", italic = true, sp = "#98beca" }
)
hi(0, "BufferLineInfoDiagnosticVisible", { bg = "#eaeaea", fg = "#5d656e" })
hi(0, "BufferLineInfoSelected", { bg = "#ffffff", bold = true, fg = "#add8e6", italic = true, sp = "#add8e6" })
hi(0, "BufferLineInfoVisible", { bg = "#eaeaea", fg = "#6a737d" })
hi(0, "BufferLineModified", { bg = "#e0e0e0", fg = "#032f62" })
hi(0, "BufferLineModifiedSelected", { bg = "#ffffff", fg = "#032f62" })
hi(0, "BufferLineModifiedVisible", { bg = "#eaeaea", fg = "#032f62" })
hi(0, "BufferLineNumbers", { bg = "#e0e0e0", fg = "#6a737d" })
hi(0, "BufferLineNumbersSelected", { bg = "#ffffff", bold = true, fg = "#24292e", italic = true })
hi(0, "BufferLineNumbersVisible", { bg = "#eaeaea", fg = "#6a737d" })
hi(0, "BufferLineOffsetSeparator", { bg = "#cccccc", fg = "#eceef1" })
hi(0, "BufferLinePick", { bg = "#e0e0e0", bold = true, fg = "#ff0000", italic = true })
hi(0, "BufferLinePickSelected", { bg = "#ffffff", bold = true, fg = "#ff0000", italic = true })
hi(0, "BufferLinePickVisible", { bg = "#eaeaea", bold = true, fg = "#ff0000", italic = true })
hi(0, "BufferLineSeparator", { bg = "#e0e0e0", fg = "#cccccc" })
hi(0, "BufferLineSeparatorSelected", { bg = "#ffffff", fg = "#cccccc" })
hi(0, "BufferLineSeparatorVisible", { bg = "#eaeaea", fg = "#cccccc" })
hi(0, "BufferLineTab", { bg = "#e0e0e0", fg = "#6a737d" })
hi(0, "BufferLineTabClose", { bg = "#e0e0e0", fg = "#6a737d" })
hi(0, "BufferLineTabSelected", { bg = "#ffffff", fg = "#41484f" })
hi(0, "BufferLineTabSeparator", { bg = "#e0e0e0", fg = "#cccccc" })
hi(0, "BufferLineTabSeparatorSelected", { bg = "#eaeaea", fg = "#cccccc" })
hi(0, "BufferLineWarning", { bg = "#e0e0e0", fg = "#6a737d", sp = "#ffa500" })
hi(0, "BufferLineWarningDiagnostic", { bg = "#e0e0e0", fg = "#5d656e", sp = "#e09100" })
hi(
  0,
  "BufferLineWarningDiagnosticSelected",
  { bg = "#ffffff", bold = true, fg = "#e09100", italic = true, sp = "#e09100" }
)
hi(0, "BufferLineWarningDiagnosticVisible", { bg = "#eaeaea", fg = "#5d656e" })
hi(0, "BufferLineWarningSelected", { bg = "#ffffff", bold = true, fg = "#ffa500", italic = true, sp = "#ffa500" })
hi(0, "BufferLineWarningVisible", { bg = "#eaeaea", fg = "#6a737d" })
hi(0, "Character", { link = "Number" })
hi(0, "CocErrorHighlight", { bg = "#ffeef0", ctermbg = 167, underline = true })
hi(0, "CocErrorSign", { bg = "#b74951", bold = true, ctermbg = 167, ctermfg = 255, fg = "#fafbfc" })
hi(0, "CocHighlightText", { bg = "#fafbfc", ctermbg = 255 })
hi(0, "CocHintSign", { bg = "#fafbfc", ctermbg = 255, ctermfg = 250, fg = "#babbbc" })
hi(0, "CocInfoHighlight", { bg = "#f1f8ff", ctermbg = 153 })
hi(0, "CocInfoSign", { bg = "#fafbfc", ctermbg = 255, ctermfg = 26, fg = "#005cc5" })
hi(0, "CocWarningHighlight", { bg = "#fffbdd", ctermbg = 230, underline = true })
hi(0, "CocWarningSign", { bg = "#fafbfc", ctermbg = 255, ctermfg = 166, fg = "#e36209" })
hi(0, "ColorColumn", { bg = "#f6f8fa", ctermbg = 255 })
hi(0, "Comment", { ctermfg = 243, fg = "#6a737d" })
hi(0, "Conceal", { ctermfg = 167, fg = "#d73a49" })
hi(0, "Constant", { ctermfg = 26, fg = "#005cc5" })
hi(0, "Cursor", { bg = "#24292e", ctermbg = 235, ctermfg = 231, fg = "#ffffff" })
hi(0, "CursorColumn", { bg = "#fffbdd", ctermbg = 230 })
hi(0, "CursorIM", { link = "Cursor" })
hi(0, "CursorLine", { bg = "#fffbdd", ctermbg = 230 })
hi(0, "CursorLineNr", { bg = "#fff5b1", ctermbg = 229, ctermfg = 243, fg = "#76787b" })
hi(0, "Define", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "Delimiter", { link = "ghNormalNoBg" })
hi(0, "DiffAdd", { bg = "#e6ffed", ctermbg = 85 })
hi(0, "DiffChange", { bg = "#fffbdd", ctermbg = 230 })
hi(0, "DiffDelete", { bg = "#ffeef0", ctermbg = 167, ctermfg = 250, fg = "#babbbc" })
hi(0, "DiffText", { bg = "#f2e496", ctermbg = 222 })
hi(0, "Directory", { link = "ghBlue" })
hi(0, "EndOfBuffer", { bg = "#fafbfc", ctermbg = 255, ctermfg = 250, fg = "#babbbc" })
hi(0, "Error", { bg = "#b74951", ctermbg = 167, ctermfg = 243, fg = "#76787b" })
hi(0, "ErrorMsg", { ctermfg = 167, fg = "#b74951" })
hi(0, "FoldColumn", { bg = "#fafbfc", ctermbg = 255, ctermfg = 153, fg = "#669cc2" })
hi(0, "Folded", { bg = "#f1f8ff", ctermbg = 153, ctermfg = 243, fg = "#76787b" })
hi(0, "Function", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "GitGutterAdd", { bg = "#edeeed", ctermbg = 255, ctermfg = 29, fg = "#22863a" })
hi(0, "GitGutterChange", { bg = "#edeeed", ctermbg = 255, ctermfg = 166, fg = "#e36209" })
hi(0, "GitGutterChangeDelete", { bg = "#edeeed", ctermbg = 255, ctermfg = 166, fg = "#e36209" })
hi(0, "GitGutterDelete", { bg = "#edeeed", ctermbg = 255, ctermfg = 124, fg = "#b31d28" })
hi(0, "GitSignsAdd", { bg = "#edeeed", ctermbg = 255, ctermfg = 29, fg = "#22863a" })
hi(0, "GitSignsAddInline", { reverse = true })
hi(0, "GitSignsAddLn", { bg = "#e6ffed", ctermbg = 85 })
hi(0, "GitSignsAddLnInline", { reverse = true })
hi(0, "GitSignsAddNr", { bg = "#fafbfc", ctermbg = 255, ctermfg = 29, fg = "#22863a" })
hi(0, "GitSignsAddPreview", { bg = "#e6ffed", ctermbg = 85 })
hi(0, "GitSignsChange", { bg = "#fafbfc", ctermbg = 255, ctermfg = 166, fg = "#e36209" })
hi(0, "GitSignsChangeInline", { reverse = true })
hi(0, "GitSignsChangeLn", { bg = "#fffbdd", ctermbg = 230 })
hi(0, "GitSignsChangeLnInline", { reverse = true })
hi(0, "GitSignsChangeNr", { bg = "#fafbfc", ctermbg = 255, ctermfg = 166, fg = "#e36209" })
hi(0, "GitSignsChangedelete", { bg = "#fafbfc", ctermbg = 255, ctermfg = 166, fg = "#e36209" })
hi(0, "GitSignsChangedeleteLn", { bg = "#fffbdd", ctermbg = 230 })
hi(0, "GitSignsChangedeleteNr", { bg = "#fafbfc", ctermbg = 255, ctermfg = 166, fg = "#e36209" })
hi(0, "GitSignsCurrentLineBlame", { bg = "#ffffff", ctermbg = 231, ctermfg = 250, fg = "#babbbc" })
hi(0, "GitSignsDelete", { bg = "#fafbfc", ctermbg = 255, ctermfg = 124, fg = "#b31d28" })
hi(0, "GitSignsDeleteInline", { reverse = true })
hi(0, "GitSignsDeleteLnInline", { reverse = true })
hi(0, "GitSignsDeleteNr", { bg = "#fafbfc", ctermbg = 255, ctermfg = 124, fg = "#b31d28" })
hi(0, "GitSignsDeletePreview", { bg = "#ffeef0", ctermbg = 167, ctermfg = 250, fg = "#babbbc" })
hi(0, "GitSignsDeleteVirtLn", { bg = "#ffeef0", ctermbg = 167, ctermfg = 250, fg = "#babbbc" })
hi(0, "GitSignsDeleteVirtLnInLine", { reverse = true })
hi(0, "GitSignsStagedAdd", { bg = "#fafbfc", fg = "#11431d" })
hi(0, "GitSignsStagedAddLn", { bg = "#e6ffed" })
hi(0, "GitSignsStagedAddNr", { bg = "#fafbfc", fg = "#11431d" })
hi(0, "GitSignsStagedChange", { bg = "#fafbfc", fg = "#713104" })
hi(0, "GitSignsStagedChangeLn", { bg = "#fffbdd" })
hi(0, "GitSignsStagedChangeNr", { bg = "#fafbfc", fg = "#713104" })
hi(0, "GitSignsStagedChangedelete", { bg = "#fafbfc", fg = "#713104" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#fffbdd" })
hi(0, "GitSignsStagedChangedeleteNr", { bg = "#fafbfc", fg = "#713104" })
hi(0, "GitSignsStagedDelete", { bg = "#fafbfc", fg = "#590e14" })
hi(0, "GitSignsStagedDeleteNr", { bg = "#fafbfc", fg = "#590e14" })
hi(0, "GitSignsStagedTopdelete", { bg = "#fafbfc", fg = "#590e14" })
hi(0, "GitSignsStagedTopdeleteNr", { bg = "#fafbfc", fg = "#590e14" })
hi(0, "GitSignsTopdelete", { bg = "#fafbfc", ctermbg = 255, ctermfg = 124, fg = "#b31d28" })
hi(0, "GitSignsTopdeleteNr", { bg = "#fafbfc", ctermbg = 255, ctermfg = 124, fg = "#b31d28" })
hi(0, "GitSignsUntracked", { bg = "#fafbfc", ctermbg = 255, ctermfg = 29, fg = "#22863a" })
hi(0, "GitSignsUntrackedLn", { bg = "#e6ffed", ctermbg = 85 })
hi(0, "GitSignsUntrackedNr", { bg = "#fafbfc", ctermbg = 255, ctermfg = 29, fg = "#22863a" })
hi(0, "GitSignsVirtLnum", { bg = "#ffeef0", ctermbg = 167, ctermfg = 250, fg = "#babbbc" })
hi(0, "Identifier", { ctermfg = 26, fg = "#005cc5" })
hi(0, "Ignore", { bg = "#ffffff", ctermbg = 231, ctermfg = 250, fg = "#babbbc" })
hi(0, "IlluminatedWordRead", { underline = true })
hi(0, "IlluminatedWordText", { underline = true })
hi(0, "IlluminatedWordWrite", { underline = true })
hi(0, "IndentBlanklineChar", { ctermfg = 250, fg = "#edeeed", nocombine = true })
hi(0, "IndentBlanklineContextChar", { ctermfg = 235, fg = "#edeeed", nocombine = true })
hi(0, "IndentBlanklineContextStart", { sp = "#24292e", underline = true })
hi(0, "IndentBlanklineSpaceChar", { ctermfg = 250, fg = "#edeeed", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { ctermfg = 250, fg = "#edeeed", nocombine = true })
hi(0, "Label", { ctermfg = 235, fg = "#24292e" })

--hi(0, "LineNr", { bg = "#fafbfc", ctermbg = 255, ctermfg = 250, fg = "#babbbc" })
hi(0, "LineNr", { bg = "#edeeed", ctermbg = 255, ctermfg = 250, fg = "#babbbc" })

hi(0, "Macro", { ctermfg = 26, fg = "#005cc5" })
hi(0, "MatchParen", { bg = "#bde0fb", ctermbg = 153, ctermfg = 17, fg = "#032f62" })
hi(0, "NERDTreeCWD", { link = "ghRed" })
hi(0, "NERDTreeDir", { link = "ghBlue" })
hi(0, "NERDTreeExecFile", { link = "ghPurple" })
hi(0, "NERDTreeFile", { link = "ghDarkBlue" })
hi(0, "NoiceAttr103", { fg = "#b74951" })
hi(0, "NoiceCmdline", {})
hi(0, "NoiceCmdlineIcon", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlineIconCalculator", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlineIconCmdline", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlineIconFilter", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlineIconHelp", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlineIconIncRename", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlineIconInput", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlineIconLua", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlineIconSearch", { ctermfg = 3, fg = "#ffa500" })
hi(0, "NoiceCmdlinePopup", { bg = "#ffffff", ctermbg = 231, ctermfg = 235, fg = "#24292e" })
hi(0, "NoiceCmdlinePopupBorder", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlinePopupBorderCalculator", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlinePopupBorderCmdline", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlinePopupBorderFilter", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlinePopupBorderHelp", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlinePopupBorderIncRename", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlinePopupBorderInput", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlinePopupBorderLua", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlinePopupBorderSearch", { ctermfg = 3, fg = "#ffa500" })
hi(0, "NoiceCmdlinePopupTitle", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCmdlinePrompt", { bold = true, ctermfg = 238, fg = "#41484f" })
hi(0, "NoiceCompletionItemKindClass", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindColor", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindConstant", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindConstructor", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindDefault", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindEnum", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindEnumMember", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindField", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindFile", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindFolder", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindFunction", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindInterface", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindKeyword", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindMethod", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindModule", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindProperty", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindSnippet", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindStruct", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindText", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindUnit", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindValue", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceCompletionItemKindVariable", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceConfirm", { bg = "#ffffff", ctermbg = 231, ctermfg = 235, fg = "#24292e" })
hi(0, "NoiceConfirmBorder", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceCursor", { bg = "#24292e", ctermbg = 235, ctermfg = 231, fg = "#ffffff" })
hi(0, "NoiceFormatConfirm", { bg = "#fffbdd", ctermbg = 230 })
hi(0, "NoiceFormatConfirmDefault", { bg = "#e4effb", ctermbg = 153 })
hi(0, "NoiceFormatDate", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoiceFormatEvent", { bg = "#ffffff", ctermbg = 231, ctermfg = 250, fg = "#babbbc" })
hi(0, "NoiceFormatKind", { bg = "#ffffff", ctermbg = 231, ctermfg = 250, fg = "#babbbc" })
hi(0, "NoiceFormatLevelDebug", { bg = "#ffffff", ctermbg = 231, ctermfg = 250, fg = "#babbbc" })
hi(0, "NoiceFormatLevelError", { ctermfg = 1, fg = "#ff0000" })
hi(0, "NoiceFormatLevelInfo", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NoiceFormatLevelOff", { bg = "#ffffff", ctermbg = 231, ctermfg = 250, fg = "#babbbc" })
hi(0, "NoiceFormatLevelTrace", { bg = "#ffffff", ctermbg = 231, ctermfg = 250, fg = "#babbbc" })
hi(0, "NoiceFormatLevelWarn", { ctermfg = 3, fg = "#ffa500" })
hi(0, "NoiceFormatProgressDone", { bg = "#ffffc5", bold = true })
hi(0, "NoiceFormatProgressTodo", { bg = "#fffbdd", ctermbg = 230 })
hi(0, "NoiceFormatTitle", { bold = true, ctermfg = 238, fg = "#41484f" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NoiceLspProgressClient", { bold = true, ctermfg = 238, fg = "#41484f" })
hi(0, "NoiceLspProgressSpinner", { ctermfg = 26, fg = "#005cc5" })
hi(0, "NoiceLspProgressTitle", { bg = "#ffffff", ctermbg = 231, ctermfg = 250, fg = "#babbbc" })
hi(0, "NoiceMini", {})
hi(0, "NoicePopup", { bg = "#f6f8fa", ctermbg = 255, ctermfg = 243, fg = "#76787b" })
hi(0, "NoicePopupBorder", { bg = "#eceef1", ctermbg = 255, ctermfg = 255, fg = "#eceef1" })
hi(0, "NoicePopupmenu", { bg = "#f6f8fa", ctermbg = 255, ctermfg = 243, fg = "#76787b" })
hi(0, "NoicePopupmenuBorder", { bg = "#eceef1", ctermbg = 255, ctermfg = 255, fg = "#eceef1" })
hi(0, "NoicePopupmenuMatch", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "NoicePopupmenuSelected", { bg = "#005cc5", bold = true, ctermbg = 26, ctermfg = 255, fg = "#f6f8fa" })
hi(0, "NoiceScrollbar", { bg = "#f6f8fa", ctermbg = 255 })
hi(0, "NoiceScrollbarThumb", { bg = "#c8ced6", ctermbg = 254 })
hi(0, "NoiceSplit", { bg = "#f6f8fa", ctermbg = 255, ctermfg = 243, fg = "#76787b" })
hi(0, "NoiceSplitBorder", { bg = "#eceef1", ctermbg = 255, ctermfg = 255, fg = "#eceef1" })
hi(0, "NoiceVirtualText", { ctermfg = 4, fg = "#add8e6" })
hi(0, "NonText", { bg = "#ffffff", ctermbg = 231, ctermfg = 250, fg = "#babbbc" })
hi(0, "Normal", { bg = "#ffffff", ctermbg = 231, ctermfg = 235, fg = "#24292e" })
hi(0, "NormalFloat", { bg = "#edeeed", ctermbg = 231, ctermfg = 235, fg = "#24292e" })
hi(0, "FloatBorder", { bg = "#24292e", ctermbg = 231, ctermfg = 235, fg = "#24292e" })
hi(0, "NotifyDEBUGBorder", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGIcon", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGTitle", { fg = "#8b8b8b" })
hi(0, "NotifyERRORBody184", { bg = "#ffffff", fg = "#f6f7f7" })
hi(0, "NotifyERRORBody227", { bg = "#ffffff", fg = "#f6f7f7" })
hi(0, "NotifyERRORBody276", { bg = "#ffffff", fg = "#ffffff" })
hi(0, "NotifyERRORBorder", { fg = "#8a1f1f" })
hi(0, "NotifyERRORBorder184", { fg = "#faf6f6" })
hi(0, "NotifyERRORBorder227", { fg = "#faf6f6" })
hi(0, "NotifyERRORBorder276", { fg = "#ffffff" })
hi(0, "NotifyERRORIcon", { fg = "#f70067" })
hi(0, "NotifyERRORIcon184", { fg = "#fff5f9" })
hi(0, "NotifyERRORIcon227", { fg = "#fff5f9" })
hi(0, "NotifyERRORIcon276", { fg = "#ffffff" })
hi(0, "NotifyERRORTitle", { fg = "#f70067" })
hi(0, "NotifyERRORTitle184", { fg = "#fff5f9" })
hi(0, "NotifyERRORTitle227", { fg = "#fff5f9" })
hi(0, "NotifyERRORTitle276", { fg = "#ffffff" })
hi(0, "NotifyINFOBorder", { fg = "#4f6752" })
hi(0, "NotifyINFOIcon", { fg = "#a9ff68" })
hi(0, "NotifyINFOTitle", { fg = "#a9ff68" })
hi(0, "NotifyTRACEBorder", { fg = "#4f3552" })
hi(0, "NotifyTRACEIcon", { fg = "#d484ff" })
hi(0, "NotifyTRACETitle", { fg = "#d484ff" })
hi(0, "NotifyWARNBorder", { fg = "#79491d" })
hi(0, "NotifyWARNIcon", { fg = "#f79000" })
hi(0, "NotifyWARNTitle", { fg = "#f79000" })
hi(0, "Pmenu", { bg = "#f6f8fa", ctermbg = 255, ctermfg = 243, fg = "#76787b" })
hi(0, "PmenuSbar", { bg = "#f6f8fa", ctermbg = 255 })
hi(0, "PmenuSel", { bg = "#005cc5", bold = true, ctermbg = 26, ctermfg = 255, fg = "#f6f8fa" })
hi(0, "PmenuThumb", { bg = "#c8ced6", ctermbg = 254 })
hi(0, "PreProc", { ctermfg = 167, fg = "#d73a49" })
hi(0, "Question", { ctermfg = 29, fg = "#22863a" })
hi(0, "QuickFixLine", { bg = "#bde0fb", bold = true, ctermbg = 153 })
hi(0, "Search", { bg = "#ffffc5", bold = true, ctermbg = 230 })
hi(0, "SignColumn", { bg = "#edeeed", ctermbg = 255, ctermfg = 250, fg = "#babbbc" })
hi(0, "Sneak", { link = "ghSneak" })
hi(0, "SneakScope", { link = "ghOverBg" })
hi(0, "Special", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "SpecialComment", { ctermfg = 235, fg = "#24292e" })
hi(0, "SpecialKey", { bg = "#ffffff", ctermbg = 231, ctermfg = 250, fg = "#babbbc" })
hi(0, "SpellBad", { ctermfg = 167, fg = "#d73a49", sp = "#d73a49", undercurl = true })
hi(0, "SpellCap", { ctermfg = 29, fg = "#22863a", sp = "#22863a", undercurl = true })
hi(0, "SpellLocal", { ctermfg = 91, fg = "#6f42c1", sp = "#ffffc5", undercurl = true })
hi(0, "SpellRare", { ctermfg = 91, fg = "#6f42c1", sp = "#6f42c1", undercurl = true })
hi(0, "StartifyHeader", { link = "ghBlue" })
hi(0, "StartifyPath", { link = "ghBlue" })
hi(0, "Statement", { ctermfg = 167, fg = "#d73a49" })
hi(0, "StatusLine", { bg = "#24292e", ctermbg = 235, ctermfg = 255, fg = "#f6f8fa" })
hi(0, "StatusLineNC", { bg = "#eceef1", ctermbg = 255, ctermfg = 243, fg = "#76787b" })
hi(0, "StorageClass", { ctermfg = 167, fg = "#d73a49" })
hi(0, "String", { ctermfg = 17, fg = "#032f62" })
hi(0, "Structure", { ctermfg = 167, fg = "#d73a49" })
hi(0, "TabLine", { bg = "#eceef1", ctermbg = 255, ctermfg = 238, fg = "#41484f" })
hi(0, "TabLineFill", { bg = "#c8ced6", ctermbg = 254, ctermfg = 254, fg = "#c8ced6" })
hi(0, "TabLineSel", { bold = true, ctermfg = 238, fg = "#41484f" })
hi(0, "Title", { bold = true, ctermfg = 238, fg = "#41484f" })
hi(0, "Todo", { ctermfg = 91, fg = "#6f42c1", underline = true })
hi(0, "TodoBgFIX", { bg = "#ff0000", bold = true, fg = "#ffffff" })
hi(0, "TodoBgHACK", { bg = "#ffa500", bold = true, fg = "#24292e" })
hi(0, "TodoBgNOTE", { bg = "#d3d3d3", bold = true, fg = "#24292e" })
hi(0, "TodoBgPERF", { bg = "#005cc5", bold = true, fg = "#ffffff" })
hi(0, "TodoBgTEST", { bg = "#005cc5", bold = true, fg = "#ffffff" })
hi(0, "TodoBgTODO", { bg = "#add8e6", bold = true, fg = "#24292e" })
hi(0, "TodoBgWARN", { bg = "#ffa500", bold = true, fg = "#24292e" })
hi(0, "TodoFgFIX", { fg = "#ff0000" })
hi(0, "TodoFgHACK", { fg = "#ffa500" })
hi(0, "TodoFgNOTE", { fg = "#d3d3d3" })
hi(0, "TodoFgPERF", { fg = "#005cc5" })
hi(0, "TodoFgTEST", { fg = "#005cc5" })
hi(0, "TodoFgTODO", { fg = "#add8e6" })
hi(0, "TodoFgWARN", { fg = "#ffa500" })
hi(0, "TodoSignFIX", { bg = "#fafbfc", fg = "#ff0000" })
hi(0, "TodoSignHACK", { bg = "#fafbfc", fg = "#ffa500" })
hi(0, "TodoSignNOTE", { bg = "#fafbfc", fg = "#d3d3d3" })
hi(0, "TodoSignPERF", { bg = "#fafbfc", fg = "#005cc5" })
hi(0, "TodoSignTEST", { bg = "#fafbfc", fg = "#005cc5" })
hi(0, "TodoSignTODO", { bg = "#fafbfc", fg = "#add8e6" })
hi(0, "TodoSignWARN", { bg = "#fafbfc", fg = "#ffa500" })
hi(0, "Type", { ctermfg = 167, fg = "#d73a49" })
hi(0, "VertSplit", { bg = "#eceef1", ctermbg = 255, ctermfg = 255, fg = "#eceef1" })
hi(0, "Visual", { bg = "#e4effb", ctermbg = 153 })
hi(0, "VisualNOS", { bg = "#f1f8ff", ctermbg = 153 })
hi(0, "WarningMsg", { ctermfg = 166, fg = "#e36209" })
hi(0, "WhichKey", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "WhichKeyBorder", { bg = "#eceef1", ctermbg = 255, ctermfg = 255, fg = "#eceef1" })
hi(0, "WhichKeyDesc", { ctermfg = 26, fg = "#005cc5" })
hi(0, "WhichKeyFloat", { bg = "#f6f8fa", ctermbg = 255, ctermfg = 243, fg = "#76787b" })
hi(0, "WhichKeyGroup", { ctermfg = 167, fg = "#d73a49" })
hi(0, "WhichKeySeparator", { ctermfg = 243, fg = "#6a737d" })
hi(0, "WhichKeyValue", { ctermfg = 243, fg = "#6a737d" })
hi(0, "Whitespace", { bg = "#ffffff", ctermbg = 231, ctermfg = 250, fg = "#babbbc" })
hi(0, "WildMenu", { bg = "#005cc5", ctermbg = 26, ctermfg = 255, fg = "#f6f8fa" })
hi(0, "airlineInsert1", { bg = "#005cc5", ctermbg = 26, ctermfg = 255, fg = "#eceef1" })
hi(0, "airlineInsert2", { bg = "#032f62", ctermbg = 17, ctermfg = 255, fg = "#eceef1" })
hi(0, "airlineN1", { bg = "#24292e", ctermbg = 235, ctermfg = 255, fg = "#eceef1" })
hi(0, "airlineN2", { bg = "#41484f", ctermbg = 238, ctermfg = 255, fg = "#eceef1" })
hi(0, "airlineN3", { bg = "#eceef1", ctermbg = 255, ctermfg = 235, fg = "#24292e" })
hi(0, "airlineReplace1", { bg = "#d73a49", ctermbg = 167, ctermfg = 255, fg = "#eceef1" })
hi(0, "airlineReplace2", { bg = "#b31d28", ctermbg = 124, ctermfg = 255, fg = "#eceef1" })
hi(0, "airlineVisual1", { bg = "#6f42c1", ctermbg = 91, ctermfg = 255, fg = "#eceef1" })
hi(0, "airlineVisual2", { bg = "#45267d", ctermbg = 237, ctermfg = 255, fg = "#eceef1" })
hi(0, "cDefine", { link = "Define" })
hi(0, "clojureDefine", { link = "Type" })
hi(0, "clojureKeyword", { link = "Identifier" })
hi(0, "clojureMacro", { link = "ghPurple" })
hi(0, "cppSTL", { link = "Function" })
hi(0, "cppSTLType", { link = "Type" })
hi(0, "diffAdded", { bg = "#e6ffed", ctermbg = 85, ctermfg = 29, fg = "#22863a" })
hi(0, "diffFile", { bg = "#f6f8fa", ctermbg = 255, ctermfg = 235, fg = "#24292e" })
hi(0, "diffIndexLine", { bg = "#f6f8fa", ctermbg = 255, ctermfg = 17, fg = "#032f62" })
hi(0, "diffLine", { bg = "#f1f8ff", ctermbg = 153, ctermfg = 243, fg = "#6a737d" })
hi(0, "diffNewFile", { bg = "#f6f8fa", ctermbg = 255, ctermfg = 235, fg = "#24292e" })
hi(0, "diffRemoved", { bg = "#ffeef0", ctermbg = 167, ctermfg = 167, fg = "#d73a49" })
hi(0, "diffSubname", { bg = "#f1f8ff", ctermbg = 153, ctermfg = 17, fg = "#032f62" })
hi(0, "ghBackground", { ctermfg = 231, fg = "#ffffff" })
hi(0, "ghBase0", { ctermfg = 235, fg = "#24292e" })
hi(0, "ghBase1", { ctermfg = 238, fg = "#41484f" })
hi(0, "ghBase2", { ctermfg = 243, fg = "#6a737d" })
hi(0, "ghBase3", { ctermfg = 243, fg = "#76787b" })
hi(0, "ghBase4", { ctermfg = 250, fg = "#babbbc" })
hi(0, "ghBlack", { ctermfg = 235, fg = "#24292e" })
hi(0, "ghBlue", { ctermfg = 26, fg = "#005cc5" })
hi(0, "ghBlue2", { ctermfg = 153, fg = "#e4effb" })
hi(0, "ghBlue3", { ctermfg = 153, fg = "#bde0fb" })
hi(0, "ghBlue4", { ctermfg = 153, fg = "#f1f8ff" })
hi(0, "ghDarkBlue", { ctermfg = 17, fg = "#032f62" })
hi(0, "ghDarkPurple", { ctermfg = 237, fg = "#45267d" })
hi(0, "ghDarkRed", { ctermfg = 124, fg = "#b31d28" })
hi(0, "ghGreen", { ctermfg = 29, fg = "#22863a" })
hi(0, "ghGrey0", { ctermfg = 254, fg = "#c8ced6" })
hi(0, "ghGrey1", { ctermfg = 255, fg = "#eceef1" })
hi(0, "ghGrey2", { ctermfg = 255, fg = "#f6f8fa" })
hi(0, "ghLightOrange", { ctermfg = 230, fg = "#fffbdd" })
hi(0, "ghLightRed", { ctermfg = 167, fg = "#ffeef0" })
hi(0, "ghNormalNoBg", { ctermfg = 235, fg = "#24292e" })
hi(0, "ghOrange", { ctermfg = 166, fg = "#e36209" })
hi(0, "ghOver", { ctermfg = 255, fg = "#f6f8fa" })
hi(0, "ghOverBg", { bg = "#f6f8fa", ctermbg = 255 })
hi(0, "ghPurple", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "ghRed", { ctermfg = 167, fg = "#d73a49" })
hi(0, "ghSneak", { bg = "#6f42c1", ctermbg = 91, ctermfg = 231, fg = "#ffffff" })
hi(0, "ghUISplit", { ctermfg = 255, fg = "#eceef1" })
hi(0, "ghYellow", { ctermfg = 230, fg = "#ffffc5" })
hi(0, "goConstants", { link = "Constant" })
hi(0, "goFunctionCall", { link = "Identifier" })
hi(0, "haskellIdentifier", { link = "Function" })
hi(0, "haskellType", { link = "Identifier" })
hi(0, "htmlArg", { link = "xmlAttrib" })
hi(0, "htmlEndTag", { link = "htmlTag" })
hi(0, "htmlH", { link = "Title" })
hi(0, "htmlLink", { link = "Underlined" })
hi(0, "htmlTag", { ctermfg = 235, fg = "#24292e" })
hi(0, "htmlTagN", { link = "htmlTag" })
hi(0, "htmlTagName", { link = "xmlTagName" })
hi(0, "jsxAttrib", { link = "xmlAttrib" })
hi(0, "jsxCloseString", { link = "jsxTag" })
hi(0, "jsxCloseTag", { link = "jsxTag" })
hi(0, "jsxComponentName", { ctermfg = 26, fg = "#005cc5" })
hi(0, "jsxEqual", { link = "Operator" })
hi(0, "jsxTag", { link = "htmlTag" })
hi(0, "jsxTagName", { link = "htmlTagName" })
hi(0, "lCursor", { bg = "#24292e", fg = "#ffffff" })
hi(0, "lualine_a_inactive", { bg = "#d3d3d3", bold = true, fg = "#5c6773" })
hi(0, "lualine_a_insert", { bg = "#86b300", bold = true, fg = "#f3f3f3" })
hi(0, "lualine_a_normal", { bg = "#59c2ff", bold = true, fg = "#f3f3f3" })
hi(0, "lualine_a_replace", { bg = "#f07178", bold = true, fg = "#f3f3f3" })
hi(0, "lualine_a_visual", { bg = "#a37acc", bold = true, fg = "#f3f3f3" })
hi(0, "lualine_b_inactive", { bg = "#d3d3d3", fg = "#5c6773" })
hi(0, "lualine_b_insert", { bg = "#d3d3d3", fg = "#5c6773" })
hi(0, "lualine_b_normal", { bg = "#d3d3d3", fg = "#5c6773" })
hi(0, "lualine_b_replace", { bg = "#d3d3d3", fg = "#5c6773" })
hi(0, "lualine_b_visual", { bg = "#d3d3d3", fg = "#5c6773" })
hi(0, "lualine_c_diagnostics_error_command", { bg = "#f3f3f3", fg = "#ff0000" })
hi(0, "lualine_c_diagnostics_error_inactive", { bg = "#f3f3f3", fg = "#ff0000" })
hi(0, "lualine_c_diagnostics_error_insert", { bg = "#f3f3f3", fg = "#ff0000" })
hi(0, "lualine_c_diagnostics_error_normal", { bg = "#f3f3f3", fg = "#ff0000" })
hi(0, "lualine_c_diagnostics_error_replace", { bg = "#f3f3f3", fg = "#ff0000" })
hi(0, "lualine_c_diagnostics_error_terminal", { bg = "#f3f3f3", fg = "#ff0000" })
hi(0, "lualine_c_diagnostics_error_visual", { bg = "#f3f3f3", fg = "#ff0000" })
hi(0, "lualine_c_diagnostics_hint_command", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_c_diagnostics_hint_inactive", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_c_diagnostics_hint_insert", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_c_diagnostics_hint_normal", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_c_diagnostics_hint_replace", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_c_diagnostics_hint_terminal", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_c_diagnostics_hint_visual", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_c_diagnostics_info_command", { bg = "#f3f3f3", fg = "#add8e6" })
hi(0, "lualine_c_diagnostics_info_inactive", { bg = "#f3f3f3", fg = "#add8e6" })
hi(0, "lualine_c_diagnostics_info_insert", { bg = "#f3f3f3", fg = "#add8e6" })
hi(0, "lualine_c_diagnostics_info_normal", { bg = "#f3f3f3", fg = "#add8e6" })
hi(0, "lualine_c_diagnostics_info_replace", { bg = "#f3f3f3", fg = "#add8e6" })
hi(0, "lualine_c_diagnostics_info_terminal", { bg = "#f3f3f3", fg = "#add8e6" })
hi(0, "lualine_c_diagnostics_info_visual", { bg = "#f3f3f3", fg = "#add8e6" })
hi(0, "lualine_c_diagnostics_warn_command", { bg = "#f3f3f3", fg = "#ffa500" })
hi(0, "lualine_c_diagnostics_warn_inactive", { bg = "#f3f3f3", fg = "#ffa500" })
hi(0, "lualine_c_diagnostics_warn_insert", { bg = "#f3f3f3", fg = "#ffa500" })
hi(0, "lualine_c_diagnostics_warn_normal", { bg = "#f3f3f3", fg = "#ffa500" })
hi(0, "lualine_c_diagnostics_warn_replace", { bg = "#f3f3f3", fg = "#ffa500" })
hi(0, "lualine_c_diagnostics_warn_terminal", { bg = "#f3f3f3", fg = "#ffa500" })
hi(0, "lualine_c_diagnostics_warn_visual", { bg = "#f3f3f3", fg = "#ffa500" })
hi(0, "lualine_c_filetype_DevIconLua_command", { bg = "#f3f3f3", fg = "#366b8a" })
hi(0, "lualine_c_filetype_DevIconLua_inactive", { bg = "#f3f3f3", fg = "#366b8a" })
hi(0, "lualine_c_filetype_DevIconLua_insert", { bg = "#f3f3f3", fg = "#366b8a" })
hi(0, "lualine_c_filetype_DevIconLua_normal", { bg = "#f3f3f3", fg = "#366b8a" })
hi(0, "lualine_c_filetype_DevIconLua_replace", { bg = "#f3f3f3", fg = "#366b8a" })
hi(0, "lualine_c_filetype_DevIconLua_terminal", { bg = "#f3f3f3", fg = "#366b8a" })
hi(0, "lualine_c_filetype_DevIconLua_visual", { bg = "#f3f3f3", fg = "#366b8a" })
hi(0, "lualine_c_filetype_DevIconTxt_command", { bg = "#f3f3f3", fg = "#447028" })
hi(0, "lualine_c_filetype_DevIconTxt_inactive", { bg = "#f3f3f3", fg = "#447028" })
hi(0, "lualine_c_filetype_DevIconTxt_insert", { bg = "#f3f3f3", fg = "#447028" })
hi(0, "lualine_c_filetype_DevIconTxt_normal", { bg = "#f3f3f3", fg = "#447028" })
hi(0, "lualine_c_filetype_DevIconTxt_replace", { bg = "#f3f3f3", fg = "#447028" })
hi(0, "lualine_c_filetype_DevIconTxt_terminal", { bg = "#f3f3f3", fg = "#447028" })
hi(0, "lualine_c_filetype_DevIconTxt_visual", { bg = "#f3f3f3", fg = "#447028" })
hi(0, "lualine_c_inactive", { bg = "#f3f3f3", fg = "#5c6773" })
hi(0, "lualine_c_normal", { bg = "#f3f3f3", fg = "#828c99" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#d3d3d3", fg = "#59c2ff" })
hi(
  0,
  "lualine_transitional_lualine_a_normal_to_lualine_c_filetype_DevIconLua_command",
  { bg = "#f3f3f3", fg = "#59c2ff" }
)
hi(
  0,
  "lualine_transitional_lualine_a_normal_to_lualine_c_filetype_DevIconLua_normal",
  { bg = "#f3f3f3", fg = "#59c2ff" }
)
hi(
  0,
  "lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconTxt_command",
  { bg = "#f3f3f3", fg = "#d3d3d3" }
)
hi(
  0,
  "lualine_transitional_lualine_b_normal_to_lualine_c_filetype_DevIconTxt_normal",
  { bg = "#f3f3f3", fg = "#d3d3d3" }
)
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_9_command", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_9_normal", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_diff_added_command", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_diff_added_normal", { bg = "#f3f3f3", fg = "#d3d3d3" })
hi(0, "lualine_x_10_command", { bg = "#f3f3f3", fg = "#005cc5" })
hi(0, "lualine_x_10_inactive", { bg = "#f3f3f3", fg = "#005cc5" })
hi(0, "lualine_x_10_insert", { bg = "#f3f3f3", fg = "#005cc5" })
hi(0, "lualine_x_10_normal", { bg = "#f3f3f3", fg = "#005cc5" })
hi(0, "lualine_x_10_replace", { bg = "#f3f3f3", fg = "#005cc5" })
hi(0, "lualine_x_10_terminal", { bg = "#f3f3f3", fg = "#005cc5" })
hi(0, "lualine_x_10_visual", { bg = "#f3f3f3", fg = "#005cc5" })
hi(0, "lualine_x_12_command", { bg = "#f3f3f3", fg = "#6f42c1" })
hi(0, "lualine_x_12_inactive", { bg = "#f3f3f3", fg = "#6f42c1" })
hi(0, "lualine_x_12_insert", { bg = "#f3f3f3", fg = "#6f42c1" })
hi(0, "lualine_x_12_normal", { bg = "#f3f3f3", fg = "#6f42c1" })
hi(0, "lualine_x_12_replace", { bg = "#f3f3f3", fg = "#6f42c1" })
hi(0, "lualine_x_12_terminal", { bg = "#f3f3f3", fg = "#6f42c1" })
hi(0, "lualine_x_12_visual", { bg = "#f3f3f3", fg = "#6f42c1" })
hi(0, "lualine_x_9_command", { bg = "#f3f3f3", fg = "#d73a49" })
hi(0, "lualine_x_9_inactive", { bg = "#f3f3f3", fg = "#d73a49" })
hi(0, "lualine_x_9_insert", { bg = "#f3f3f3", fg = "#d73a49" })
hi(0, "lualine_x_9_normal", { bg = "#f3f3f3", fg = "#d73a49" })
hi(0, "lualine_x_9_replace", { bg = "#f3f3f3", fg = "#d73a49" })
hi(0, "lualine_x_9_terminal", { bg = "#f3f3f3", fg = "#d73a49" })
hi(0, "lualine_x_9_visual", { bg = "#f3f3f3", fg = "#d73a49" })
hi(0, "lualine_x_diff_added_command", { bg = "#f3f3f3", fg = "#22863a" })
hi(0, "lualine_x_diff_added_inactive", { bg = "#f3f3f3", fg = "#22863a" })
hi(0, "lualine_x_diff_added_insert", { bg = "#f3f3f3", fg = "#22863a" })
hi(0, "lualine_x_diff_added_normal", { bg = "#f3f3f3", fg = "#22863a" })
hi(0, "lualine_x_diff_added_replace", { bg = "#f3f3f3", fg = "#22863a" })
hi(0, "lualine_x_diff_added_terminal", { bg = "#f3f3f3", fg = "#22863a" })
hi(0, "lualine_x_diff_added_visual", { bg = "#f3f3f3", fg = "#22863a" })
hi(0, "lualine_x_diff_modified_command", { bg = "#f3f3f3", fg = "#e36209" })
hi(0, "lualine_x_diff_modified_inactive", { bg = "#f3f3f3", fg = "#e36209" })
hi(0, "lualine_x_diff_modified_insert", { bg = "#f3f3f3", fg = "#e36209" })
hi(0, "lualine_x_diff_modified_normal", { bg = "#f3f3f3", fg = "#e36209" })
hi(0, "lualine_x_diff_modified_replace", { bg = "#f3f3f3", fg = "#e36209" })
hi(0, "lualine_x_diff_modified_terminal", { bg = "#f3f3f3", fg = "#e36209" })
hi(0, "lualine_x_diff_modified_visual", { bg = "#f3f3f3", fg = "#e36209" })
hi(0, "lualine_x_diff_removed_command", { bg = "#f3f3f3", fg = "#b31d28" })
hi(0, "lualine_x_diff_removed_inactive", { bg = "#f3f3f3", fg = "#b31d28" })
hi(0, "lualine_x_diff_removed_insert", { bg = "#f3f3f3", fg = "#b31d28" })
hi(0, "lualine_x_diff_removed_normal", { bg = "#f3f3f3", fg = "#b31d28" })
hi(0, "lualine_x_diff_removed_replace", { bg = "#f3f3f3", fg = "#b31d28" })
hi(0, "lualine_x_diff_removed_terminal", { bg = "#f3f3f3", fg = "#b31d28" })
hi(0, "lualine_x_diff_removed_visual", { bg = "#f3f3f3", fg = "#b31d28" })
hi(0, "markdownCode", { link = "pandocDelimitedCodeBlock" })
hi(0, "markdownHeadingDelimiter", { link = "pandocAtxStart" })
hi(0, "markdownListMarker", { link = "pandocOperator" })
hi(0, "markdownRule", { link = "Title" })
hi(0, "pandocAtxStart", { ctermfg = 250, fg = "#babbbc" })
hi(0, "pandocCitekey", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "pandocDelimitedCodeBlock", { ctermfg = 237, fg = "#45267d" })
hi(0, "pandocNoFormatted", { bg = "#fafbfc", ctermbg = 255, ctermfg = 235, fg = "#24292e" })
hi(0, "pandocOperator", { ctermfg = 167, fg = "#d73a49" })
hi(0, "pandocPCite", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "perlSharpBang", { link = "Special" })
hi(0, "pythonBuiltin", { link = "Identifier" })
hi(0, "qfLineNr", { bg = "#fafbfc", ctermbg = 255, ctermfg = 243, fg = "#76787b" })
hi(0, "rubyClass", { link = "PreProc" })
hi(0, "rubyConstant", { link = "Define" })
hi(0, "rubyDefine", { link = "PreProc" })
hi(0, "rubyInclude", { link = "PreProc" })
hi(0, "rubySharpBang", { link = "Special" })
hi(0, "rustAttribute", { link = "ghBase0" })
hi(0, "rustCommentLineDoc", { link = "ghBase2" })
hi(0, "rustDerive", { link = "rustAttribute" })
hi(0, "rustDeriveTrait", { link = "ghDarkPurple" })
hi(0, "rustIdentifier", { link = "Function" })
hi(0, "rustModPath", { link = "Define" })
hi(0, "schemeFunc", { link = "Statement" })
hi(0, "shDeref", { link = "Identifier" })
hi(0, "shVariable", { link = "Function" })
hi(0, "sneakLabel", { link = "ghSneak" })
hi(0, "texMath", { ctermfg = 26, fg = "#005cc5" })
hi(0, "texSection", { link = "Title" })
hi(0, "texStatement", { ctermfg = 167, fg = "#d73a49" })
hi(0, "texType", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "tomlKey", { link = "ghBlack" })
hi(0, "tomlTable", { link = "ghPurple" })
hi(0, "typescriptBraces", { link = "ghBlack" })
hi(0, "typescriptParens", { link = "ghBlack" })
hi(0, "vimAugroupKey", { link = "Identifier" })
hi(0, "vimAutoCmd", { link = "Identifier" })
hi(0, "vimAutoEvent", { link = "Identifier" })
hi(0, "vimCommand", { link = "Statement" })
hi(0, "vimGroup", { link = "Statement" })
hi(0, "vimHiGroup", { link = "ghOrange" })
hi(0, "vimHiTerm", { link = "ghBlack" })
hi(0, "vimHighlight", { link = "Identifier" })
hi(0, "vimMap", { link = "Identifier" })
hi(0, "vimNotFunc", { link = "Statement" })
hi(0, "vimOption", { link = "Identifier" })
hi(0, "vimParenSep", { link = "Delimiter" })
hi(0, "vimSynType", { link = "Identifier" })
hi(0, "vimSyntax", { link = "Identifier" })
hi(0, "vimUserCommand", { link = "Identifier" })
hi(0, "vimUserFunc", { link = "ghPurple" })
hi(0, "xmlAttrib", { ctermfg = 91, fg = "#6f42c1" })
hi(0, "xmlEndTag", { ctermfg = 29, fg = "#22863a" })
hi(0, "xmlTag", { ctermfg = 29, fg = "#22863a" })
hi(0, "xmlTagName", { ctermfg = 29, fg = "#22863a" })
hi(0, "yamlBlockMappingKey", { link = "ghGreen" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#babbbc"
g.terminal_color_1 = "#d73a49"
g.terminal_color_2 = "#3ebc5c"
g.terminal_color_3 = "#f18338"
g.terminal_color_4 = "#005cc5"
g.terminal_color_5 = "#6f42c1"
g.terminal_color_6 = "#005cc5"
g.terminal_color_7 = "#41484f"
g.terminal_color_8 = "#76787b"
g.terminal_color_9 = "#b31d28"
g.terminal_color_10 = "#22863a"
g.terminal_color_11 = "#e36209"
g.terminal_color_12 = "#032f62"
g.terminal_color_13 = "#45267d"
g.terminal_color_14 = "#032f62"
g.terminal_color_15 = "#24292e"
